/**
* THIS FILE IS AUTOGENERATED BY grunt-preload-assets
*
* Object containing game assets
*
* @example
*
*		var width = filesManifest["img/side_blue1.png"].w
*
*/ 
var filesManifest = filesManifest || {};
filesManifest = {
	"test/fixtures/genericButton.png": {},
	"test/fixtures/genericButtonOver.png": {},
	"test/fixtures/parallaxHill1.png": {},
	"test/fixtures/sky.png": {},
	"test/fixtures/image2.jpg": {}
};
